services:
  init-keyfile:
    image: mongo:6.0
    container_name: init_keyfile
    command: >
      sh -c "
      mkdir -p /etc/mongodb/pki &&
      if [ ! -f /etc/mongodb/pki/keyfile ]; then
        echo 'Generating keyfile...';
        openssl rand -base64 756 > /etc/mongodb/pki/keyfile &&
        chown 999:999 /etc/mongodb/pki/keyfile &&
        chmod 400 /etc/mongodb/pki/keyfile;
      else
        echo 'Keyfile already exists.';
        chown 999:999 /etc/mongodb/pki/keyfile &&
        chmod 400 /etc/mongodb/pki/keyfile;
      fi
      "
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
    networks:
      - mongo-cluster
    restart: "on-failure"

  # Config Server Replica Set
  config1:
    container_name: config1
    image: mongo:6.0
    hostname: config1
    command: mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - config1_data:/data/db
    networks:
      - mongo-cluster

  config2:
    container_name: config2
    image: mongo:6.0
    hostname: config2
    command: mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - config2_data:/data/db
    networks:
      - mongo-cluster

  config3:
    container_name: config3
    image: mongo:6.0
    hostname: config3
    command: mongod --configsvr --replSet configrs --port 27019 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - config3_data:/data/db
    networks:
      - mongo-cluster

  # Single Shard Replica Set
  shard1_1:
    container_name: shard1_1
    image: mongo:6.0
    hostname: shard1_1
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - shard1_1_data:/data/db
    networks:
      - mongo-cluster

  shard1_2:
    container_name: shard1_2
    image: mongo:6.0
    hostname: shard1_2
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - shard1_2_data:/data/db
    networks:
      - mongo-cluster

  shard1_3:
    container_name: shard1_3
    image: mongo:6.0
    hostname: shard1_3
    command: mongod --shardsvr --replSet shard1rs --port 27018 --bind_ip_all
    depends_on:
      - init-keyfile
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - shard1_3_data:/data/db
    networks:
      - mongo-cluster

  # Mongos Router
  mongos:
    container_name: mongos
    image: mongo:6.0
    hostname: mongos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    command: ["bash", "/mongodb-init-sharded.sh"]
    depends_on:
      - config1
      - config2
      - config3
      - shard1_1
      - shard1_2
      - shard1_3
    volumes:
      - mongo-keyfile-vol:/etc/mongodb/pki
      - ./mongodb-init-sharded.sh:/mongodb-init-sharded.sh:ro
    healthcheck:
      test: ["CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - mongo-cluster

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - mongo-cluster

networks:
  mongo-cluster:

volumes:
  mongo-keyfile-vol:
  config1_data:
  config2_data:
  config3_data:
  shard1_1_data:
  shard1_2_data:
  shard1_3_data:
  minio_data:
